    # Generated by Django 6.0.6 on 2026-07-04 06:59   database ma student ko data store garna ko lagi table create garna ko lagi migration file generate gareko ho.

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('roll', models.IntegerField()),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField()),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=40)),
                ('is_present', models.BooleanField()),
            ],
        ),
    ]
